kind: Deployment
apiVersion: apps/v1
metadata:
   name: manojphaju
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: manojphaju
   template:
      metadata:
        labels:
          app: manojphaju
      spec:
       containers:
        - name: manojphaju
          image: manojphaju/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80